---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2023/9/29 1:54 AM
---

package.cpath = "./?.so"
local elfmap = require("elfmap")
local pystring = require("pystring")

assert(string, "need install pystring lib for test.")

local function getLibcPath()
    local cmd = io.popen("ldconfig -p")
    local res = cmd:read("*all")
    cmd:close()

    local libs = pystring.split(res, "\n")
    for _, lib in ipairs(libs) do
        local info = pystring.strip(lib)
        if pystring.startswith(info, "libc.so") then
            local _, dst = unpack(pystring.split(info, " => "))
            return dst
        end
    end
end

local libc = getLibcPath()
local m = elfmap.new(libc)
local count = 0
for _, start, stop, sym in m:maps() do
    count = count + 1
end
assert(count == m:count(), string.format("map: %d, count:%d", count, m:count()))

local start, _ = m:symbol("pthread_self")
assert(start > 0)
local sym = m:query(start)
assert(sym == "pthread_self")

assert(m:query(0) == "[unknown]")

m = elfmap.new("/lib64/libpthread.so")
print(m:count())